stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "gravel3497/glowinfront"

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker tag $DOCKER_IMAGE $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

deploy_frontend:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull $DOCKER_IMAGE:latest
    - docker stop frontend || true
    - docker rm frontend || true
    - docker run -d --name frontend -p 3000:80 $DOCKER_IMAGE:latest
  only:
    - main
